language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - tip

script:
  - go vet github.com/echlebek/strictjson
  - go test -coverprofile={{.Dir}}/coverprofile github.com/echlebek/strictjson

after_success:
  - bash <(curl -s https://codecov.io/bash) -f {{.Dir}}/coverprofile
